# Generated by Django 5.1.6 on 2025-02-26 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='nickname',
            field=models.CharField(default='Anonymous', max_length=30),
        ),
    ]
