# Generated by Django 5.1.6 on 2025-02-26 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(default='media/profile_pics/default.jpg', upload_to='media/profile_pics/'),
        ),
    ]
