# Generated by Django 5.1.6 on 2025-02-27 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_post_likes_delete_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
    ]
